### ISSUE TITLE
Problems with umlauts

### ISSUE THREAD

**Issue by horald** [sn0opy/MPD-Webinterface#13]
Hello,
it is a nice Webinterface. Unfortunately the umlauts are not displayed correctly. "Radio Köln" becomes "Radio K?ln". Where can I set the umlauts?
Best regards
Horst

**Comment by sn0opy** [comment]
Hey, this project is basically abandoned. I'm not using mpd, nor the webinterface nor Linux as my desktop environment at all. I did manage to get a mopidy/ncmpcpp docker setup up and running for testing, so bear in mind, this is not an actual mpd nor any local files I'm running in this test setup.

Usually my terminal is able to display special characters, so I assume that ncmpcpp  has some hickups here, but mopidy and my webinterface do display them just fine. Even japanese characters are displayed properly.

You could look into https://github.com/sn0opy/mpdinterface2 instead. It isn't maintained by me either, but it's a bit more up to date.

![image](https://user-images.githubusercontent.com/49074/68260130-41312900-003c-11ea-9c23-44aefd8bf163.png)
